# Generated by Django 3.0.6 on 2020-06-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vuelo', models.CharField(max_length=100)),
                ('nombre_aerolinea', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('disponibilidad', models.IntegerField()),
                ('ciudad_origen', models.CharField(max_length=100)),
                ('ciudad_destino', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
            ],
        ),
    ]
