# Generated by Django 3.0.6 on 2020-06-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_hotel', models.CharField(max_length=100)),
                ('lugar', models.CharField(max_length=100)),
                ('disponibilidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateField()),
                ('estrellas', models.IntegerField()),
            ],
        ),
    ]
