# Generated by Django 3.0.6 on 2020-05-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.FloatField()),
                ('aero_ida', models.CharField(max_length=100)),
                ('aero_vuelta', models.CharField(max_length=100)),
                ('vuelo_ida', models.CharField(max_length=100)),
                ('vuelo_vuelta', models.CharField(max_length=100)),
                ('fecha_ida', models.DateTimeField()),
                ('fecha_vuelta', models.DateTimeField()),
                ('hotel', models.CharField(max_length=100)),
                ('hotel_noches', models.PositiveSmallIntegerField()),
                ('excur_1', models.CharField(max_length=100)),
                ('excur_2', models.CharField(max_length=100)),
                ('excur_3', models.CharField(max_length=100)),
            ],
        ),
    ]
