# Generated by Django 3.0.6 on 2020-06-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.FloatField(default=1200)),
                ('cantidad_p', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('ciudad_origen', models.CharField(max_length=100)),
                ('ciudad_destino', models.CharField(max_length=100)),
                ('excursion1', models.CharField(max_length=100)),
                ('excursion2', models.CharField(max_length=100)),
                ('excursion3', models.CharField(max_length=100)),
                ('hotel', models.CharField(max_length=100)),
                ('vuelo_ida', models.CharField(max_length=100)),
                ('vuelo_vuelta', models.CharField(max_length=100)),
            ],
        ),
    ]
