# Generated by Django 3.0.6 on 2020-05-21 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='hotel_hab',
            field=models.PositiveSmallIntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
