# Generated by Django 3.0.6 on 2020-05-21 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0002_paquete_hotel_hab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='hotel_hab',
        ),
    ]
