# Generated by Django 3.0.6 on 2020-06-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0002_paquete_estrellas'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='reservado',
            field=models.BooleanField(default=False),
        ),
    ]
