# Generated by Django 3.0.6 on 2020-05-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0003_remove_paquete_hotel_hab'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='hotel_hab',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
