# Generated by Django 3.0.6 on 2020-05-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0004_paquete_hotel_hab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='hotel_hab',
        ),
        migrations.AddField(
            model_name='paquete',
            name='hotel_habit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
