# Generated by Django 3.0.6 on 2020-05-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0005_auto_20200521_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='hotel_habit',
        ),
        migrations.AddField(
            model_name='paquete',
            name='hotel_nro',
            field=models.IntegerField(default=0),
        ),
    ]
