# Generated by Django 3.0.6 on 2020-05-21 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0006_auto_20200521_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paquete',
            old_name='hotel_nro',
            new_name='hotel_hab',
        ),
    ]
