# Generated by Django 3.0.6 on 2020-05-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0007_auto_20200521_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='hotel_hab',
        ),
        migrations.AddField(
            model_name='paquete',
            name='hotel_num',
            field=models.IntegerField(default=0),
        ),
    ]
